[package]
name = "sui_options"
edition = "2024.beta"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/testnet"
override = true

[dependencies.MoveStdlib]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/move-stdlib"
rev = "framework/testnet"
override = true

[dependencies.wormhole]
local = "D:/wormhole/sui/wormhole"
override = true

[dependencies.Pyth]
local = "D:/pyth-crosschain/target_chains/sui/contracts"

[addresses]
sui_options = "0x0"
pyth = "0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837"
wormhole = "0xf47329f4344f3bf0f8e436e2f7b485466cff300f12a166563995d3888c296a94"
